name: Selenium IDE Website Tester
description: Verify functionality on your website using Selenium tests from Selenium IDE.
author: Dylan700

branding:
  icon: check-square
  color: green

inputs:
  url: 
    description: 'URL to test'
    required: true
    default: ""

runs:
  using: composite
  steps: 
    - name: Get Docker Image
      shell: bash
      run: docker pull docker.pkg.github.com/dylan700/selenium-ide-runner/selenium-ide-runner:latest
    - name: Create Screenshots Directory
      shell: bash
      run: mkdir -p $GITHUB_WORKSPACE/screenshots
    - name: Create Reports Directory
      shell: bash
      run: mkdir -p $GITHUB_WORKSPACE/reports
    - name: Run Dockerfile
      shell: bash
      run: docker run -v /dev/shm:/dev/shm -v ./:$GITHUB_WORKSPACE -e GITHUB_WORKSPACE=$GITHUB_WORKSPACE -e BASE_URL=${{inputs.url}} -u root selenium-ide-runner
    - name: Upload Screenshots 
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: ./screenshots/*.png
    - name: Generate Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
          name: Selenium Test Report            
          path: ./reports/*.xml
          reporter: jest-junit