name: Test Action
on: [pull_request]
jobs:
  build:
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
      actions: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Action
      uses: Dylan700/selenium-ide-action@latest 
