name: Docker Build and Run Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
        registry:
            image: registry:2
            ports:
                - 5000:5000
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: localhost:5000/test/${{github.sha}}:test
    - name: Run Docker image
      run: docker run -v /dev/shm:/dev/shm -v ./:$GITHUB_WORKSPACE -e GITHUB_WORKSPACE=$GITHUB_WORKSPACE -e BASE_URL="" -u root  --privileged --network host --rm localhost:5000/test/${{github.sha}}:test